language: perl
perl:
  - "5.30-shrplib"
env: PERL_CPANM_OPT="--notest --force --skip-satisfied"
addons:
  apt:
    update: true
    packages:
      - diction
before_install:
  - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
install:
  - export PATH=$PATH:$HOME/bin
  - export PERL5LIB=$PERL5LIB:$(pwd)/lib/perl5
  - export PERL5LIB=$PERL5LIB:$HOME/perl5:$HOME/perl5/lib/perl5
before_script:
  - ls -F # if this test fails, just be sure what the directory is
  - pwd; pwd -P
script:
  - cpanm --installdeps --notest .
  - perl Makefile.PL 
  - make test

